# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [3]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1, 2, 3])

# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]])

# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([[[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]],
              
              [[10, 11, 12],
               [13, 14, 15],
               [16, 17, 18]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [6]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.shape, a1.ndim, a1.dtype, a1.size, type(a1)

((3,), 1, dtype('int32'), 3, numpy.ndarray)

In [7]:
# Attributes of 2-dimensional array
a2.shape, a2.ndim, a2.dtype, a2.size, type(a2)

((3, 3), 2, dtype('int32'), 9, numpy.ndarray)

In [8]:
# Attributes of 3-dimensional array
a3.shape, a3.ndim, a3.dtype, a3.size, type(a3)

((2, 3, 3), 3, dtype('int32'), 18, numpy.ndarray)

In [9]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd

df = pd.DataFrame(a2)

In [11]:
df

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [10]:
# Create an array of shape (10, 2) with only ones
ones = np.ones(shape=(10, 2))

In [12]:
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [13]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros(shape=(7, 2, 3))

In [14]:
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [18]:
# Create an array within a range of 0 and 100 with step 3
range_array = np.arange(0, 100, 3)

In [19]:
range_array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [23]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_array_int = np.random.randint(0, 10, size=(7, 2))

In [24]:
random_array_int

array([[1, 3],
       [8, 1],
       [5, 8],
       [7, 9],
       [9, 4],
       [9, 0],
       [1, 2]])

In [29]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
random_array_fl = np.random.rand(3, 5)

In [30]:
random_array_fl

array([[0.10221101, 0.47619439, 0.84714544, 0.61124933, 0.1825026 ],
       [0.50193811, 0.28894088, 0.487223  , 0.48353986, 0.42259563],
       [0.27275611, 0.93200087, 0.45384127, 0.97118838, 0.87297234]])

In [32]:
# Set the random seed to 42
np.random.seed(seed=42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
array46 = np.random.randint(0, 10, size=(4, 6))

In [34]:
array46

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [39]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
array37 = np.random.randint(1, 10, size=(3, 7))

# Find the unique numbers in the array you just created
array37_unique = np.unique(array37)

In [40]:
array37

array([[2, 5, 8, 9, 9, 1, 9],
       [7, 9, 8, 1, 8, 8, 3],
       [1, 8, 3, 3, 1, 5, 7]])

In [41]:
array37_unique

array([1, 2, 3, 5, 7, 8, 9])

In [42]:
# Find the 0'th index of the latest array you created
array37[0]

array([2, 5, 8, 9, 9, 1, 9])

In [44]:
# Get the first 2 rows of latest array you created
array37[:2]

array([[2, 5, 8, 9, 9, 1, 9],
       [7, 9, 8, 1, 8, 8, 3]])

In [45]:
# Get the first 2 values of the first 2 rows of the latest array
array37[:2, :2]

array([[2, 5],
       [7, 9]])

In [46]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
rand_arr = np.random.randint(0, 10, size=(3, 5))
ones_arr = np.ones(shape=(3, 5))

In [47]:
rand_arr

array([[9, 8, 6, 8, 7],
       [1, 0, 6, 6, 7],
       [4, 2, 7, 5, 2]])

In [48]:
ones_arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [49]:
# Add the two arrays together
rand_arr + ones_arr

array([[10.,  9.,  7.,  9.,  8.],
       [ 2.,  1.,  7.,  7.,  8.],
       [ 5.,  3.,  8.,  6.,  3.]])

In [50]:
# Create another array of ones of shape (5, 3)
ones = np.ones(shape=(5, 3))

In [51]:
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [52]:
# Try add the array of ones and the other most recent array together
rand_arr + ones

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [53]:
# Create another array of ones of shape (3, 5)
ones = np.ones(shape=(3, 5))

In [54]:
# Subtract the new array of ones from the other most recent array
rand_arr - ones

array([[ 8.,  7.,  5.,  7.,  6.],
       [ 0., -1.,  5.,  5.,  6.],
       [ 3.,  1.,  6.,  4.,  1.]])

In [55]:
# Multiply the ones array with the latest array
ones * rand_arr

array([[9., 8., 6., 8., 7.],
       [1., 0., 6., 6., 7.],
       [4., 2., 7., 5., 2.]])

In [59]:
# Take the latest array to the power of 2 using '**'
rand_arr**2

array([[81, 64, 36, 64, 49],
       [ 1,  0, 36, 36, 49],
       [16,  4, 49, 25,  4]], dtype=int32)

In [60]:
# Do the same thing with np.square()
np.square(rand_arr)

array([[81, 64, 36, 64, 49],
       [ 1,  0, 36, 36, 49],
       [16,  4, 49, 25,  4]], dtype=int32)

In [61]:
# Find the mean of the latest array using np.mean()
np.mean(rand_arr)

5.2

In [62]:
# Find the maximum of the latest array using np.max()
np.max(rand_arr)

9

In [63]:
# Find the minimum of the latest array using np.min()
np.min(rand_arr)

0

In [64]:
# Find the standard deviation of the latest array
np.std(rand_arr)

2.6882460204874605

In [65]:
# Find the variance of the latest array
np.var(rand_arr)

7.2266666666666675

In [66]:
# Reshape the latest array to (3, 5, 1)
np.reshape(rand_arr, newshape=(3, 5, 1))

array([[[9],
        [8],
        [6],
        [8],
        [7]],

       [[1],
        [0],
        [6],
        [6],
        [7]],

       [[4],
        [2],
        [7],
        [5],
        [2]]])

In [67]:
# Transpose the latest array
rand_arr.T

array([[9, 1, 4],
       [8, 0, 2],
       [6, 6, 7],
       [8, 6, 5],
       [7, 7, 2]])

What does the transpose do?

In [68]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
a33 = np.random.randint(0, 10, size=(3, 3))
a32 = np.random.randint(0, 10, size=(3, 2))

In [69]:
a33

array([[0, 2, 4],
       [2, 0, 4],
       [9, 6, 6]])

In [70]:
a32

array([[8, 9],
       [9, 2],
       [6, 0]])

In [72]:
# Perform a dot product on the two newest arrays you created
# np.dot(a33, a32)
a33.dot(a32)

array([[ 42,   4],
       [ 40,  18],
       [162,  93]])

In [73]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
a1 = np.random.randint(0, 10, size=(4, 3))
a2 = np.random.randint(0, 10, size=(4, 3))

In [74]:
a1

array([[3, 3, 4],
       [6, 6, 3],
       [6, 2, 5],
       [1, 9, 8]])

In [75]:
a2

array([[4, 5, 3],
       [9, 6, 8],
       [6, 0, 0],
       [8, 8, 3]])

In [76]:
# Perform a dot product on the two newest arrays you created
a1.dot(a2)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [77]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
a1.dot(a2.T)

array([[ 39,  77,  18,  60],
       [ 63, 114,  36, 105],
       [ 49, 106,  36,  79],
       [ 73, 127,   6, 104]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [78]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
a1 = np.random.randint(0, 10, size=(4, 3))
a2 = np.random.randint(0, 10, size=(4, 3))

In [79]:
# Compare the two arrays with '>'
a1>a2

array([[ True, False,  True],
       [ True,  True, False],
       [ True, False,  True],
       [ True,  True,  True]])

What happens when you compare the arrays with `>`?

In [80]:
# Compare the two arrays with '>='
a1>=a2

array([[ True, False,  True],
       [ True,  True, False],
       [ True, False,  True],
       [ True,  True,  True]])

In [81]:
# Find which elements of the first array are greater than 7
a1 > 7

array([[ True, False, False],
       [False, False,  True],
       [False, False, False],
       [ True, False, False]])

In [82]:
# Which parts of each array are equal? (try using '==')
a1 == a2

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [88]:
a1

array([[2, 6, 8],
       [5, 7, 8],
       [0, 2, 4],
       [5, 7, 9]])

In [91]:
# Sort one of the arrays you just created in ascending order
a1_sorted = np.sort(a1)

In [92]:
a1_sorted

array([[2, 6, 8],
       [5, 7, 8],
       [0, 2, 4],
       [5, 7, 9]])

In [93]:
# Sort the indexes of one of the arrays you just created
np.argsort(a1)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [94]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(a1)

11

In [95]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(a1)

6

In [96]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(a1, axis=1)

array([2, 2, 2, 2], dtype=int64)

In [97]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(a1, axis=0)

array([2, 2, 2], dtype=int64)

In [101]:
# Create an array of normally distributed random numbers
norm_arr = np.random.normal(size=(5,))
norm_arr

array([-1.16867804,  1.14282281,  0.75193303,  0.79103195, -0.90938745])

In [103]:
# Create an array with 10 evenly spaced numbers between 1 and 100
spaced_arr = np.arange(1, 100, 10)
spaced_arr

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.